# Generated by Django 5.2.4 on 2025-08-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('dhis2_auth', '0002_alter_dhis2user_dhis2_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the assessment', max_length=255)),
                ('org_unit_id', models.CharField(db_index=True, max_length=255)),
                ('org_unit_name', models.CharField(blank=True, max_length=255)),
                ('periods', models.JSONField(default=list, help_text='List of periods used in the assessment')),
                ('user_notes', models.TextField(blank=True, help_text='User notes and comments')),
                ('indicator_data', models.JSONField(default=dict, help_text='Indicator data with values for each period')),
                ('calculated_scores', models.JSONField(default=dict, help_text='Calculated scores and grades')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the assessment')),
                ('session_key', models.CharField(blank=True, help_text='DHIS2 session key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_assessments', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Saved Assessment',
                'verbose_name_plural': 'Saved Assessments',
                'db_table': 'saved_assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_unit_id'], name='saved_asses_org_uni_fc1efc_idx'), models.Index(fields=['created_at'], name='saved_asses_created_719d7e_idx'), models.Index(fields=['created_by'], name='saved_asses_created_aa4b78_idx')],
            },
        ),
    ]
