# Generated by Django 5.2.4 on 2025-08-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_savedassessment'),
        ('dhis2_auth', '0002_alter_dhis2user_dhis2_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('manual_override', 'Manual Override'), ('dhis2_sync', 'DHIS2 Sync'), ('score_calculation', 'Score Calculation'), ('assessment_save', 'Assessment Save'), ('assessment_update', 'Assessment Update'), ('assessment_delete', 'Assessment Delete')], max_length=20)),
                ('entity_type', models.CharField(choices=[('indicator_data', 'Indicator Data'), ('indicator_score', 'Indicator Score'), ('objective_score', 'Objective Score'), ('sector_score', 'Sector Score'), ('saved_assessment', 'Saved Assessment'), ('data_sync', 'Data Sync')], max_length=20)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('change_reason', models.CharField(choices=[('manual_entry', 'Manual Entry'), ('dhis2_sync', 'DHIS2 Sync'), ('score_override', 'Score Override'), ('data_correction', 'Data Correction'), ('system_calculation', 'System Calculation'), ('user_request', 'User Request')], default='user_request', max_length=20)),
                ('change_description', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('org_unit_id', models.CharField(blank=True, max_length=255)),
                ('org_unit_name', models.CharField(blank=True, max_length=255)),
                ('assessment_period', models.CharField(blank=True, max_length=50)),
                ('indicator_id', models.CharField(blank=True, max_length=255)),
                ('objective_id', models.CharField(blank=True, max_length=255)),
                ('is_conflict_resolution', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, max_length=50)),
                ('resolution_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='audit_logs_action__94af82_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['org_unit_id', 'assessment_period'], name='audit_logs_org_uni_77c670_idx'), models.Index(fields=['is_conflict_resolution', 'created_at'], name='audit_logs_is_conf_fc34fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('data_conflict', 'Data Conflict'), ('score_conflict', 'Score Conflict'), ('timestamp_conflict', 'Timestamp Conflict'), ('user_conflict', 'User Conflict')], max_length=20)),
                ('entity_type', models.CharField(choices=[('indicator_data', 'Indicator Data'), ('indicator_score', 'Indicator Score'), ('objective_score', 'Objective Score'), ('sector_score', 'Sector Score'), ('saved_assessment', 'Saved Assessment'), ('data_sync', 'Data Sync')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('manual_data', models.JSONField(default=dict)),
                ('dhis2_data', models.JSONField(default=dict)),
                ('conflict_fields', models.JSONField(default=list)),
                ('resolution_method', models.CharField(choices=[('manual_wins', 'Manual Override Wins'), ('dhis2_wins', 'DHIS2 Data Wins'), ('merge', 'Merge Data'), ('keep_both', 'Keep Both Versions'), ('escalate', 'Escalate to Admin')], default='manual_wins', max_length=20)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('org_unit_id', models.CharField(blank=True, max_length=255)),
                ('assessment_period', models.CharField(blank=True, max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Conflict Resolution',
                'verbose_name_plural': 'Conflict Resolutions',
                'db_table': 'conflict_resolutions',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['conflict_type', 'resolution_status'], name='conflict_re_conflic_7164c2_idx'), models.Index(fields=['entity_type', 'entity_id'], name='conflict_re_entity__0a82f6_idx'), models.Index(fields=['org_unit_id', 'assessment_period'], name='conflict_re_org_uni_2efc04_idx')],
            },
        ),
    ]
