# Generated by Django 5.2.4 on 2025-08-10 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auditlog_conflictresolution'),
        ('configurations', '0003_milestone_score'),
        ('dhis2_auth', '0002_alter_dhis2user_dhis2_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit_id', models.CharField(db_index=True, max_length=255)),
                ('org_unit_name', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField(blank=True, help_text='Manual score for this milestone (-2 to +2)', null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)])),
                ('score_color', models.CharField(blank=True, max_length=7)),
                ('score_label', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='User notes about this milestone score')),
                ('is_manual_override', models.BooleanField(default=True, help_text='Milestone scores are always manual')),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(auto_now_add=True)),
                ('assessment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_scores', to='configurations.assessmentperiod')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='configurations.milestone')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_scores', to='configurations.objective')),
                ('override_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_score_overrides', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Milestone Score',
                'verbose_name_plural': 'Milestone Scores',
                'db_table': 'milestone_scores',
                'ordering': ['objective__order', 'milestone__order'],
                'indexes': [models.Index(fields=['org_unit_id', 'assessment_period'], name='milestone_s_org_uni_a3d4cf_idx'), models.Index(fields=['objective', 'org_unit_id'], name='milestone_s_objecti_0358e1_idx'), models.Index(fields=['milestone', 'org_unit_id'], name='milestone_s_milesto_a99825_idx'), models.Index(fields=['created_at'], name='milestone_s_created_58aa5a_idx')],
                'unique_together': {('milestone', 'org_unit_id', 'assessment_period')},
            },
        ),
    ]
