# Generated by Django 5.2.4 on 2025-08-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_milestonescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provided', models.BooleanField(default=True)),
                ('current_meets_target', models.BooleanField(null=True)),
                ('previous_meets_target', models.BooleanField(null=True)),
                ('change_category', models.CharField(choices=[('>5%', 'Improvement >5%'), ('5%<=C>-5%', 'Stable (-5% to +5%)'), ('-10%<C<=-5%', 'Small decline (-10% to -5%)'), ('<=-10%', 'Large decline (≤-10%)')], max_length=20, null=True)),
                ('gap_category', models.CharField(choices=[('<=10%', 'Close to target (≤10%)'), ('10%<PT<=40%', 'Moderately far (10-40%)'), ('>40%', 'Far from target (>40%)')], max_length=20, null=True)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('target_gap', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.indicatorscore')),
            ],
            options={
                'verbose_name': 'Scoring Context',
                'verbose_name_plural': 'Scoring Contexts',
                'db_table': 'scoring_contexts',
            },
        ),
        migrations.AddField(
            model_name='indicatorscore',
            name='scoring_context',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.scoringcontext'),
        ),
    ]
