# Generated by Django 5.2.4 on 2025-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_scoringcontext_indicatorscore_scoring_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorscore',
            name='remarks',
            field=models.TextField(blank=True, help_text='User remarks about this indicator score'),
        ),
    ]
