# Generated by Django 5.2.4 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_indicatorscore_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcontext',
            name='change_category',
            field=models.CharField(choices=[('>5%', 'Improvement >5%'), ('-5%<C<=5%', 'Stable (-5% to +5%)'), ('-10%<C<=-5%', 'Small decline (-10% to -5%)'), ('<=-10%', 'Large decline (≤-10%)')], max_length=20, null=True),
        ),
    ]
