# Generated by Django 5.2.4 on 2026-08-05 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_scoringcontext_change_category'),
        ('dhis2_auth', '0002_alter_dhis2user_dhis2_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAssessmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_unit_group_id', models.CharField(max_length=255)),
                ('org_unit_group_name', models.CharField(blank=True, max_length=255)),
                ('org_unit_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('org_unit_level_name', models.CharField(blank=True, max_length=255)),
                ('periods', models.JSONField(default=list)),
                ('period_labels', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('total_facilities', models.PositiveIntegerField(default=0)),
                ('processed_facilities', models.PositiveIntegerField(default=0)),
                ('succeeded_facilities', models.PositiveIntegerField(default=0)),
                ('failed_facilities', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_assessment_jobs', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Bulk Assessment Job',
                'verbose_name_plural': 'Bulk Assessment Jobs',
                'db_table': 'bulk_assessment_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkAssessmentJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit_id', models.CharField(db_index=True, max_length=255)),
                ('org_unit_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.bulkassessmentjob')),
                ('saved_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_job_items', to='assessments.savedassessment')),
            ],
            options={
                'verbose_name': 'Bulk Assessment Job Item',
                'verbose_name_plural': 'Bulk Assessment Job Items',
                'db_table': 'bulk_assessment_job_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkassessmentjob',
            index=models.Index(fields=['created_by', 'created_at'], name='bulk_assess_created_5e1187_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkassessmentjob',
            index=models.Index(fields=['status'], name='bulk_assess_status_0dfaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkassessmentjobitem',
            index=models.Index(fields=['job', 'status'], name='bulk_assess_job_id_e8f11d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkassessmentjobitem',
            unique_together={('job', 'org_unit_id')},
        ),
    ]
