# Generated by Django 5.2.4 on 2025-08-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhis2_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_uid', models.CharField(max_length=255, unique=True)),
                ('dhis2_code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_group', models.BooleanField(default=False, help_text='Whether this is a system-defined group')),
                ('dhis2_created', models.DateTimeField(blank=True, null=True)),
                ('dhis2_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Org Unit Group',
                'verbose_name_plural': 'Org Unit Groups',
                'db_table': 'org_unit_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dhis2_uid', models.CharField(max_length=255, unique=True)),
                ('dhis2_code', models.CharField(blank=True, max_length=50)),
                ('can_view_data', models.BooleanField(default=True)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('parent_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_levels', to='organisation.orgunitlevel')),
            ],
            options={
                'verbose_name': 'Org Unit Level',
                'verbose_name_plural': 'Org Unit Levels',
                'db_table': 'org_unit_levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_uid', models.CharField(max_length=255, unique=True)),
                ('dhis2_code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_leaf', models.BooleanField(default=False)),
                ('can_view_data', models.BooleanField(default=True)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('dhis2_created', models.DateTimeField(blank=True, null=True)),
                ('dhis2_last_updated', models.DateTimeField(blank=True, null=True)),
                ('dhis2_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organisation.orgunit')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='organisation.orgunitlevel')),
            ],
            options={
                'verbose_name': 'Org Unit',
                'verbose_name_plural': 'Org Units',
                'db_table': 'org_units',
                'ordering': ['level__level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('dhis2_instance_url', models.URLField()),
                ('total_org_units', models.PositiveIntegerField(default=0)),
                ('successful_org_units', models.PositiveIntegerField(default=0)),
                ('failed_org_units', models.PositiveIntegerField(default=0)),
                ('total_levels', models.PositiveIntegerField(default=0)),
                ('successful_levels', models.PositiveIntegerField(default=0)),
                ('failed_levels', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('dhis2_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_sync_logs', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Org Unit Sync Log',
                'verbose_name_plural': 'Org Unit Sync Logs',
                'db_table': 'org_unit_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOrgUnitAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_data', models.BooleanField(default=True)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=True)),
                ('include_children', models.BooleanField(default=True, help_text='Whether access includes child org units')),
                ('include_descendants', models.BooleanField(default=True, help_text='Whether access includes all descendant org units')),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary org unit for this user')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to='dhis2_auth.dhis2user')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='organisation.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_access', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'User Org Unit Access',
                'verbose_name_plural': 'User Org Unit Access',
                'db_table': 'user_org_unit_access',
                'ordering': ['user__dhis2_username', 'org_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisation.orgunitgroup')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='organisation.orgunit')),
            ],
            options={
                'verbose_name': 'Org Unit Group Membership',
                'verbose_name_plural': 'Org Unit Group Memberships',
                'db_table': 'org_unit_group_memberships',
                'ordering': ['org_unit__name', 'group__name'],
                'unique_together': {('org_unit', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['dhis2_uid'], name='org_units_dhis2_u_2a6254_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['level', 'parent'], name='org_units_level_i_91dba6_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['is_active'], name='org_units_is_acti_ac1347_idx'),
        ),
        migrations.AddIndex(
            model_name='userorgunitaccess',
            index=models.Index(fields=['user', 'is_active'], name='user_org_un_user_id_5c2320_idx'),
        ),
        migrations.AddIndex(
            model_name='userorgunitaccess',
            index=models.Index(fields=['org_unit', 'is_active'], name='user_org_un_org_uni_f26e53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userorgunitaccess',
            unique_together={('user', 'org_unit')},
        ),
    ]
