# Generated by Django 5.2.4 on 2025-08-01 00:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for this category', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicator Category',
                'verbose_name_plural': 'Indicator Categories',
                'db_table': 'indicator_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the indicator', max_length=255)),
                ('dhis2_uid', models.CharField(help_text='DHIS2 UID of the indicator/data element', max_length=255, unique=True)),
                ('indicator_type', models.CharField(choices=[('indicator', 'Indicator'), ('dataElement', 'Data Element'), ('calculated', 'Calculated')], default='indicator', help_text='Type of DHIS2 object', max_length=20)),
                ('formula', models.TextField(blank=True, help_text='Optional formula for calculated indicators (e.g., (uid1 / uid2) * 100)', null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target value for this indicator', max_digits=10, null=True)),
                ('target_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', help_text='Whether higher or lower values are better', max_length=10)),
                ('min_score', models.IntegerField(default=-2, help_text='Minimum score for this indicator', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('max_score', models.IntegerField(default=2, help_text='Maximum score for this indicator', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this indicator is active and should be included in calculations')),
                ('description', models.TextField(blank=True, help_text='Description of what this indicator measures')),
                ('dhis2_name', models.CharField(blank=True, help_text='Original name from DHIS2', max_length=255)),
                ('dhis2_description', models.TextField(blank=True, help_text='Original description from DHIS2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time this indicator was synced from DHIS2', null=True)),
            ],
            options={
                'verbose_name': 'Tracked Indicator',
                'verbose_name_plural': 'Tracked Indicators',
                'db_table': 'tracked_indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, help_text='Minimum value for this threshold', max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, help_text='Maximum value for this threshold', max_digits=10)),
                ('score', models.IntegerField(help_text='Score assigned to values in this range', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for this threshold', max_length=7)),
                ('label', models.CharField(help_text="Human-readable label for this threshold (e.g., 'Excellent', 'Poor')", max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='indicators.trackedindicator')),
            ],
            options={
                'verbose_name': 'Indicator Threshold',
                'verbose_name_plural': 'Indicator Thresholds',
                'db_table': 'indicator_thresholds',
                'ordering': ['indicator', 'min_value'],
                'unique_together': {('indicator', 'min_value', 'max_value')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this indicator within the category', max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='indicators.indicatorcategory')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='indicators.trackedindicator')),
            ],
            options={
                'verbose_name': 'Indicator Category Mapping',
                'verbose_name_plural': 'Indicator Category Mappings',
                'db_table': 'indicator_category_mappings',
                'unique_together': {('indicator', 'category')},
            },
        ),
    ]
