# Generated by Django 5.2.4 on 2025-08-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackedindicator',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Tracked Indicator', 'verbose_name_plural': 'Tracked Indicators'},
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within objective'),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='indicator_number',
            field=models.CharField(blank=True, help_text="Indicator number in Excel format (e.g., '1.1', '1.2')", max_length=20),
        ),
    ]
