# Generated by Django 5.2.4 on 2025-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_trackedindicator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedindicator',
            name='dhis2_uid',
            field=models.CharField(blank=True, help_text='DHIS2 UID of the indicator/data element (leave blank for manual entry)', max_length=255, null=True, unique=True),
        ),
    ]
