# Generated by Django 5.2.4 on 2025-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_trackedindicator_dhis2_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedindicator',
            name='denominator',
            field=models.TextField(blank=True, help_text='Denominator description for the indicator calculation', null=True),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='numerator',
            field=models.TextField(blank=True, help_text='Numerator description for the indicator calculation', null=True),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='source_of_data',
            field=models.CharField(blank=True, help_text='Source of data for this indicator (e.g., DHIS2, Financial Report, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='target_display',
            field=models.CharField(blank=True, help_text="Formatted target display (e.g., '20-50', '100%', '85.0')", max_length=100, null=True),
        ),
    ]
