# Generated by Django 5.2.4 on 2025-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_trackedindicator_denominator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedindicator',
            name='close_gap_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Threshold for 'close to target' (default: 10.0)", max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='decline_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Threshold for significant decline (default: 10.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='far_gap_threshold',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text="Threshold for 'far from target' (default: 40.0)", max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='improvement_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Threshold for '>5%' improvement (default: 5.0)", max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='stability_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Threshold for stable performance (default: 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='target_measurement_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('ABSOLUTE', 'Absolute Number'), ('RATIO', 'Ratio')], default='PERCENTAGE', help_text='Type of target measurement', max_length=20),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='target_operator',
            field=models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or equal'), ('<', 'Less than'), ('<=', 'Less than or equal'), ('=', 'Equal to')], default='>=', help_text='Operator for target comparison (e.g., >5%)', max_length=10),
        ),
    ]
