# Generated by Django 5.2.4 on 2025-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_trackedindicator_close_gap_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedindicator',
            name='target_format',
            field=models.CharField(choices=[('SINGLE', 'Single Value'), ('RANGE', 'Range'), ('MINIMUM', 'Minimum'), ('MAXIMUM', 'Maximum')], default='SINGLE', help_text='Type of target (single value, range, minimum, or maximum)', max_length=20),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='target_lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Lower limit for range targets (e.g., for '1-5' range, this would be 1)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trackedindicator',
            name='target_upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Upper limit for range targets (e.g., for '1-5' range, this would be 5)", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackedindicator',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target value for this indicator (single value or upper bound for ranges)', max_digits=10, null=True),
        ),
    ]
