# Generated by Django 5.2.4 on 2025-11-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_trackedindicator_target_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedindicator',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Target value for this indicator (single value or upper bound for ranges)', max_digits=10, null=True),
        ),
    ]
