# Generated by Django 5.2.4 on 2025-08-01 02:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhis2_auth', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('storage', 'Storage'), ('formatting', 'Formatting'), ('security', 'Security'), ('performance', 'Performance'), ('notification', 'Notification')], max_length=20)),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_config', models.BooleanField(default=False, help_text='Whether this is a system configuration that cannot be modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Export Configuration',
                'verbose_name_plural': 'Export Configurations',
                'db_table': 'export_configurations',
                'ordering': ['config_type', 'config_key'],
                'unique_together': {('config_type', 'config_key')},
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('export_format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('html', 'HTML')], default='excel', max_length=10)),
                ('export_type', models.CharField(choices=[('dashboard_summary', 'Dashboard Summary'), ('objective_performance', 'Objective Performance'), ('indicator_performance', 'Indicator Performance'), ('org_unit_performance', 'Org Unit Performance'), ('trend_analysis', 'Trend Analysis'), ('comparative_analysis', 'Comparative Analysis'), ('custom_report', 'Custom Report')], default='dashboard_summary', max_length=50)),
                ('template_config', models.JSONField(default=dict, help_text='Template configuration including layout, styling, and data mapping')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_template', models.BooleanField(default=False, help_text='Whether this is a system-defined template')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this template is available to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_templates', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'db_table': 'export_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_cron', models.CharField(blank=True, help_text='Custom cron expression for custom frequency', max_length=100)),
                ('schedule_parameters', models.JSONField(default=dict, help_text='Schedule-specific parameters')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('successful_runs', models.PositiveIntegerField(default=0)),
                ('failed_runs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_schedules', to='dhis2_auth.dhis2user')),
                ('org_unit_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_schedules', to='organisation.orgunit')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_schedules', to='exports.exporttemplate')),
            ],
            options={
                'verbose_name': 'Export Schedule',
                'verbose_name_plural': 'Export Schedules',
                'db_table': 'export_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('export_format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('html', 'HTML')], max_length=10)),
                ('export_type', models.CharField(choices=[('dashboard_summary', 'Dashboard Summary'), ('objective_performance', 'Objective Performance'), ('indicator_performance', 'Indicator Performance'), ('org_unit_performance', 'Org Unit Performance'), ('trend_analysis', 'Trend Analysis'), ('comparative_analysis', 'Comparative Analysis'), ('custom_report', 'Custom Report')], max_length=50)),
                ('export_parameters', models.JSONField(default=dict, help_text='Export parameters including filters, date ranges, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the exported file should be deleted', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='dhis2_auth.dhis2user')),
                ('org_unit_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='organisation.orgunit')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='exports.exporttemplate')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exports.exportjob')),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'db_table': 'export_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['export_job', 'timestamp'], name='export_logs_export__618b68_idx'), models.Index(fields=['level', 'timestamp'], name='export_logs_level_2133fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', 'priority'], name='export_jobs_status_992e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['created_by', 'created_at'], name='export_jobs_created_e84f99_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['export_type', 'export_format'], name='export_jobs_export__162507_idx'),
        ),
    ]
