# Generated by Django 5.2.4 on 2025-08-01 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_username', models.CharField(max_length=255, unique=True)),
                ('dhis2_instance_url', models.URLField()),
                ('dhis2_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dhis2_org_units', models.JSONField(blank=True, default=list)),
                ('dhis2_authorities', models.JSONField(blank=True, default=list)),
                ('dhis2_user_groups', models.JSONField(blank=True, default=list)),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('current_session_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'DHIS2 User',
                'verbose_name_plural': 'DHIS2 Users',
                'db_table': 'dhis2_users',
            },
        ),
        migrations.CreateModel(
            name='DHIS2Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('dhis2_instance_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dhis2_auth.dhis2user')),
            ],
            options={
                'verbose_name': 'DHIS2 Session',
                'verbose_name_plural': 'DHIS2 Sessions',
                'db_table': 'dhis2_sessions',
            },
        ),
    ]
