# Generated by Django 5.2.4 on 2025-08-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2user',
            name='dhis2_username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dhis2user',
            unique_together={('dhis2_username', 'dhis2_instance_url')},
        ),
    ]
