# Generated by Django 5.2.4 on 2025-08-01 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Period name (e.g., 'Q1 2024')", max_length=255, unique=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='quarterly', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the assessment period')),
                ('end_date', models.DateField(help_text='End date of the assessment period')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this period is active')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Period',
                'verbose_name_plural': 'Assessment Periods',
                'db_table': 'assessment_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Objective name (e.g., 'Objective 1')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the objective')),
                ('code', models.CharField(help_text="Short code for the objective (e.g., 'OBJ1')", max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this objective is active')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for this objective', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
                'db_table': 'objectives',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Configuration value (JSON format)')),
                ('config_type', models.CharField(choices=[('scoring', 'Scoring Configuration'), ('display', 'Display Configuration'), ('integration', 'Integration Configuration'), ('notification', 'Notification Configuration'), ('export', 'Export Configuration')], default='scoring', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WeightingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the weighting scheme', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the weighting scheme')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scheme is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default scheme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weighting Scheme',
                'verbose_name_plural': 'Weighting Schemes',
                'db_table': 'weighting_schemes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Rule name (e.g., 'Excellent Performance')", max_length=255)),
                ('performance_type', models.CharField(choices=[('gap', 'Target Gap'), ('change', 'Percent Change'), ('absolute', 'Absolute Value')], default='gap', help_text='Type of performance measurement', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum threshold value', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum threshold value', max_digits=10, null=True)),
                ('score', models.IntegerField(help_text='Score assigned to this performance range', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for this score', max_length=7)),
                ('label', models.CharField(help_text="Human-readable label (e.g., 'Excellent', 'Poor')", max_length=50)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority for rule matching (higher = more important)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Rule',
                'verbose_name_plural': 'Scoring Rules',
                'db_table': 'scoring_rules',
                'ordering': ['performance_type', 'priority', 'min_value'],
                'unique_together': {('performance_type', 'min_value', 'max_value')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this indicator within the objective', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_weights', to='indicators.trackedindicator')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='configurations.objective')),
            ],
            options={
                'verbose_name': 'Indicator Weight',
                'verbose_name_plural': 'Indicator Weights',
                'db_table': 'indicator_weights',
                'ordering': ['objective__order', 'weight'],
                'unique_together': {('objective', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='ObjectiveWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of this objective in the scheme', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_weights', to='configurations.objective')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_weights', to='configurations.weightingscheme')),
            ],
            options={
                'verbose_name': 'Objective Weight',
                'verbose_name_plural': 'Objective Weights',
                'db_table': 'objective_weights',
                'ordering': ['scheme', 'objective__order'],
                'unique_together': {('scheme', 'objective')},
            },
        ),
    ]
