# Generated by Django 5.2.4 on 2025-08-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Milestone name (e.g., 'MS 1.1')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the milestone')),
                ('code', models.CharField(help_text="Short code for the milestone (e.g., 'MS1.1')", max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within objective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this milestone is active')),
                ('color', models.CharField(default='#ffc107', help_text='Hex color code for this milestone (yellow for Excel)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'db_table': 'milestones',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='objective',
            name='color',
            field=models.CharField(default='#fd7e14', help_text='Hex color code for this objective (orange for Excel)', max_length=7),
        ),
        migrations.AddField(
            model_name='objective',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Associated milestone for this objective', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='configurations.milestone'),
        ),
    ]
