# Generated by Django 5.2.4 on 2025-08-10 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_milestone_alter_objective_color_objective_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='score',
            field=models.IntegerField(default=-2, help_text='Manual score for this milestone (-2 to +2)', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
